dist: bionic
language: php

env:
  global:
    - SETUP=stable

matrix:
  fast_finish: true
  include:
    - php: 7.3
#    - php: 7.3
#      env: SETUP=lowest
    - php: 7.4
#    - php: 7.4
#      env: SETUP=lowest

addons:
  chrome: stable

branches:
  only:
    - master
    - dev

cache:
  directories:
    - $HOME/.composer/cache
    - node_modules
    - vendor

services:
  - memcached
  - redis-server
  - mysql

before_install:
  - phpenv config-rm xdebug.ini || true
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - printf "\n" | pecl install -f redis


install:
  - cp .env.travis .env
  - mysql -e 'CREATE DATABASE testing;'
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
#  - if [[ $SETUP = 'stable' ]]; then travis_retry composer install --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
#  - if [[ $SETUP = 'lowest' ]]; then travis_retry composer install --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi
  - php artisan key:generate
  - php artisan migrate:fresh --seed
  - php artisan dusk:chrome-driver
  - chmod -R 0755 vendor/laravel/dusk/bin/

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - php artisan code:analyse --level=7
  - vendor/bin/phpunit
  - php artisan dusk
